// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go

// Package usercache is a generated GoMock package.
package usercache

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	users "github.com/tagpro/zd-search-cli/pkg/store/users"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// GetUsers mocks base method.
func (m *MockCache) GetUsers(key, input string) (users.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", key, input)
	ret0, _ := ret[0].(users.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockCacheMockRecorder) GetUsers(key, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockCache)(nil).GetUsers), key, input)
}

// Optimise mocks base method.
func (m *MockCache) Optimise() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Optimise")
	ret0, _ := ret[0].(error)
	return ret0
}

// Optimise indicates an expected call of Optimise.
func (mr *MockCacheMockRecorder) Optimise() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Optimise", reflect.TypeOf((*MockCache)(nil).Optimise))
}
